~F12::Reload
~F11::ExitApp

MsgBox,
    ( LTrim ; has LTrim, this line deep === test2 line deep +1
        deep+1...
        deep+1...
        deep+1...
    )

MsgBox, % "
    ( LTrim ; has LTrim, this line deep === test2 line deep +1
        deep+1...
        deep+1...
        deep+1...
    )"

MsgBox, % "
    ( ;not has LTrim, this line deep === test2 line deep +1
deepRaw...
    deepRaw...
            deepRaw...
deepRaw...
                            deepRaw...
                        deepRaw...
    )"

MsgBox,
    ( ;not has LTrim, this line deep === test2 line deep +1
deepRaw...
    deepRaw...
            deepRaw...
deepRaw...
                            deepRaw...
                        deepRaw...
    )


test1 := "
    ( LTrim ; has LTrim, this line deep === test2 line deep +1
        deep+1...
        deep+1...
        deep+1...
    )" ; this line deep === test2 line deep +1
----------------------------------------------------------------------------------------------------
test2 := "
        (  ;not has LTrim, this line deep === test2 line deep +1
deepRaw...
    deepRaw...
            deepRaw...
deepRaw...
                            deepRaw...
                        deepRaw...
        )" ;this line deep === test2 line deep +1


bar(str1, opt) {

}

foo() {

    bar("
        (
            w            -> up
            s            -> down
            a            -> left
            d            -> right
        )", "w",0)
    ;    ^mulit-line end
}
