ControlGet, OutputVar, List
ControlGet, OutputVar, Checked
ControlGet, OutputVar, Enabled
ControlGet, OutputVar, Visible
ControlGet, OutputVar, Tab
ControlGet, OutputVar, FindString
ControlGet, OutputVar, Choice
ControlGet, OutputVar, LineCount
ControlGet, OutputVar, CurrentLine
ControlGet, OutputVar, CurrentCol
ControlGet, OutputVar, Line
ControlGet, OutputVar, Selected
ControlGet, OutputVar, Style
ControlGet, OutputVar, ExStyle
ControlGet, OutputVar, Hwnd